### PR TITLE
Mention rules array change in release history.

### PR DESCRIPTION
**Pull request by lgolding**
@michaelcfanning FYI. I'm going to merge this, and then I am going to `cherry-pick` this commit and your previous history update into `master`

### CODE REVIEW

**Comment by lgolding** [comment]
@rtaket is added to the review. #Closed

**Comment by lgolding** [comment]
@cfaucon is added to the review. #Closed

**Comment by lgolding** [comment]
@michaelcfanning is added to the review. #Closed

**Comment by lgolding** [comment]
@michaelcfanning FYI only.

**Comment by michaelcfanning** [comment]
@lgolding great. From this, I assume that you intend master to reflect all changes up to but not including TC31 approved revisions. Correct? If we, we need to update the schema version from 2018-11-28 to 2019-01-09.

**Comment by lgolding** [comment]
@michaelcfanning, @rtaket

Yes, that is correct. We have to be careful, though:

1. The NuGet publishing changes are in `master` but not yet in `develop`.
2. Your previous three commits in `master` are also not yet in `develop`.
3. The release history changes are in `develop` but not yet in `master`
4. The schema version change is in _neither_ `develop` nor `master`.

!

Therefore my plan is:

1. cherry-pick the release history changes from `develop` to `master`.
2. Make the schema version change directly in `master`.
3. **IDEALLY, WE WOULD PUBLISH THE NUGET PACKAGES FROM MASTER AT THIS POINT.**
4. cherry-pick the schema version change, and Michael’s previous three commits, from `master` to `develop`.


---
In reply to: [458708273](https://github.com/Microsoft/sarif-sdk/pull/1243#issuecomment-458708273) [](ancestors = 458708273)

**Pull request merged**
