### PR TITLE
Enabling dotnet-format in pipeline

### PR DESCRIPTION
**Pull request by eddynaka**
## Changes
- enable github actions
- enable dotnet-format to force some rules (using ordered, new line, header, etc).

### CODE REVIEW

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by michaelcfanning** [comment]
> 

do we need:
--exclude .\src\packages --exclude .\bld


---
Refers to: .github/workflows/dotnet-format.yml:25 in b36b78e. [](commit_id = b36b78ea0007ebbf4609fbae2458057e9048c3be, deletion_comment = False)

**Comment by eddynaka** [comment]
> 

since we don't have source code in packages and in bld, we don't need to add those.

---
In reply to: [714738359](https://github.com/microsoft/sarif-sdk/pull/2123#issuecomment-714738359) [](ancestors = 714738359)

---
Refers to: .github/workflows/dotnet-format.yml:25 in b36b78e. [](commit_id = b36b78ea0007ebbf4609fbae2458057e9048c3be, deletion_comment = False)

**Comment by eddynaka** [comment]
> 

and, the other thing, when the pipeline runs, we won't have those folders, because we are not building it.

---
In reply to: [714740327](https://github.com/microsoft/sarif-sdk/pull/2123#issuecomment-714740327) [](ancestors = 714740327,714738359)

---
Refers to: .github/workflows/dotnet-format.yml:25 in b36b78e. [](commit_id = b36b78ea0007ebbf4609fbae2458057e9048c3be, deletion_comment = False)

**Comment by michaelcfanning** [comment]
> 

got it.

---
In reply to: [714740678](https://github.com/microsoft/sarif-sdk/pull/2123#issuecomment-714740678) [](ancestors = 714740678,714740327,714738359)

---
Refers to: .github/workflows/dotnet-format.yml:25 in b36b78e. [](commit_id = b36b78ea0007ebbf4609fbae2458057e9048c3be, deletion_comment = False)

**Pull request merged**
