### PR TITLE
Make results object optional. If present, the array shall contain at …

### PR DESCRIPTION
**Pull request by michaelcfanning**
…least one item. @lgolding @nguerrera @davidknise @bobschumaker

### CODE REVIEW

**Comment by BillyONeal** [comment]
Why prohibit an empty array?

**Comment by lgolding** [comment]
Yes, that is an error. Empty array is explicitly required for a tool that detects no problems.

**Comment by michaelcfanning** [comment]
@BillyONeal @lgolding  updated

**Comment by lgolding** [comment]
:+1:

**Pull request merged**
