### PR TITLE
ESLint sarif formatter improvements

### PR DESCRIPTION
**Pull request by yongyan-gh**
# Descriptions

Some improvements for ESLint SARIF formatter:
- Including endLine/endColumn in region.
- Upgrade lock file version to version 2.
- Fix 2 vulnerable npm package references.

### CODE REVIEW

**Comment by yongyan-gh** [comment]
The fix resolved below vulnerable packages issue reported by Github.

Note the first alert is for [src/TypeScript/Sarif.SDK/package-lock.json](https://github.com/microsoft/sarif-sdk/blob/-/src/TypeScript/Sarif.SDK/package-lock.json), it needs a separated fix.

image

**Review by eddynaka — APPROVED** [review]

**Comment by michaelcfanning** [comment]
@marmegh and @EasyRhinoMSFT , we need to start getting more eyes on SARIF formatting work. @colawton docs/user-facing output will be a prominent part of this.

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by scalvert** [comment]
Sorry to be late to reviewing this. We've moved the source to the [`sarif-js-sdk`](https://github.com/microsoft/sarif-js-sdk), but I was remiss in removing the source from this repo in favor of that, and republishing from that repo.

We should determine a plan to:

- decommission the source from this repo
- publish a new version from that repo (it can likely just be a patch, since it'll only be changing the repository path

This should not break/interrupt consumers, since the packages will be functionally the same.

**Comment by eddynaka** [comment]
Hi @scalvert ,

Yong just created a PR moving the code.
so, once we merge that, we can delete this and only use the sarif-js-sdk :)

**Comment by scalvert** [comment]
I saw that, which is what prompted me to write my comment. I've also commented on @yongyan-gh's PR in that repo. Thanks!

**Pull request merged**
