### PR TITLE
HdfConverter: Map Impact=0 to Kind=Not Applicable

### PR DESCRIPTION
**Pull request by candrews**
Per @Amndeep7 and @aaronlippold of the MITRE SAF team, which is the team that manages the Heimdall Data Format (HDF), `impact` of `0` indicates not applicable. See: https://github.com/microsoft/sarif-sdk/issues/2695#issuecomment-1648728655

### CODE REVIEW

**Comment by michaelcfanning** [comment]
Can you add something like this to ReleaseHistory.md? Obviously, update this text as you see fit to reflect the work/intent. :)

BUG: Improve  `HdfConverter1 SARIF conversion to properly map various properties (e.g., `kind`, `level`, `rank`) and generally prepare converted SARIF for ingestion to GitHub Advanced Security.

**Comment by candrews** [comment]
> Can you add something like this to ReleaseHistory.md?

Done!

**Review by michaelcfanning — APPROVED** [review]

**Comment by michaelcfanning** [comment]
OK! Should automerge shortly. You need a release after this or do we have more good stuff coming?

**Comment by candrews** [comment]
A release would be fantastic!

I'm sure there's no more coming... But this is all I know of at the moment :-)

**Comment by candrews** [comment]
I'm looking forward to the release, thank you again!

**Comment by michaelcfanning** [comment]
In flight.

**Comment by michaelcfanning** [comment]
@candrews https://www.nuget.org/packages/Sarif.Sdk/4.3.0. thanks for the contributions! really helpful.

**Pull request merged**
