### PR TITLE
The final batch!

### PR DESCRIPTION
**Pull request by EasyRhin0**

### CODE REVIEW

**Comment by lgolding** [comment]
@EasyRhin0 Why did this one not do appveyor?

**Comment by EasyRhin0** [comment]
I thought it did? I had three green circles

**Comment by EasyRhin0** [comment]
Actually I know it did, I did a "woohoo" when it succeeded.

**Comment by EasyRhin0** [comment]
Ah, click Show details next to the merge event

**Comment by lgolding** [comment]
Yes, I see. This is odd for two reasons:
1. On this PR, it didn't show the details by default.
2. When I click Show Details, I don't get the three circles, I get two little check marks.

I wonder if they just changed the UI. Anyway, it's all good.

**Pull request merged**
