### PR TITLE
Suppressions for 2202

### PR DESCRIPTION
**Pull request by jericahuang**
Suppressed CA2202 warnings following up from yesterday's meeting

@lgolding @michaelcfanning @kschecht @Rolstenhouse @jinujoseph

### CODE REVIEW

**Comment by michaelcfanning** [comment]
What the heck happened to this Global Suppressions file? :) VS has inserted a BOM, github now  believes it's a binary flie and codeflow is not displaying correctly. @lgolding, can you investigate?

Literal intended change looks fine, btw. You could try resaving the file to zap the BOM. I believe Larry told how to do so in previous conversation.

**Comment by michaelcfanning** [comment]
+1 after BOM removal.

**Comment by lgolding** [comment]
It's not just that it's inserting a BOM; it's saving it as UTF-16 (two bytes per Unicode character). Yes, resave the file with "UTF-8 Encoding (No Signature)" as I suggested in previous PR. See me if you need help.

**Comment by lgolding** [comment]
:shipit:

**Comment by lgolding** [comment]
> // You do not need to add suppressions to this file manually.

I looked at this file in CodeFlow and it is now absolutely fine. Go ahead and merge.

---
Refers to: src/Sarif/GlobalSuppressions.cs:26 in 2dc12ac. [](commit_id = 2dc12ac4bfca30e26e2eb8496b987e4159c94262, deletion_comment = False)

**Pull request merged**
