### PR TITLE
Remove Viewer projects from Everything.sln & build

### PR DESCRIPTION
**Pull request by EasyRhin0**

### CODE REVIEW

**Comment by EasyRhin0** [comment]
This is in preparation for moving the Viewer to its own repo.

**Comment by EasyRhin0** [comment]
Still have to remove tests from RunUnitTests.ps1 and the BuildAndTest,cmd

**Comment by lgolding** [comment]
@EasyRhin0 Yes. My point is, there's no reason to edit Everything.sln. Just get rid of it.

**Comment by EasyRhin0** [comment]
Oh sorry, I misread.

**Comment by EasyRhin0** [comment]
It was some kind of weird problem when we were adding .NET Core support, don't remember exactly.

**Pull request merged**
