### PR TITLE
Add `expiryDateUtc` property to `suppression`.

### PR DESCRIPTION
**Pull request by yongyan-gh**
## Description:

Add `expiryDateUtc` property to `suppression` to SARIF 2.2.0 WIP JSON schema.

### CODE REVIEW

**Comment by yongyan-gh** [comment]
>         },

@stacywray pls review the new `expiryDateUtc` property

---
Refers to: src/Sarif/Schemata/sarif-2.2.0-wip.json:2741 in b360d6c. [](commit_id = b360d6c5ebd0cfb46375d7017bbdab2dc3d879f5, deletion_comment = False)

**Comment by yongyan-gh** [comment]
>         },

update the description Stacy suggested

---
In reply to: [1846007134](https://github.com/microsoft/sarif-sdk/pull/2744#issuecomment-1846007134) [](http://example.com/codeflow?ancestors=1846007134)

---
Refers to: src/Sarif/Schemata/sarif-2.2.0-wip.json:2741 in b360d6c. [](commit_id = b360d6c5ebd0cfb46375d7017bbdab2dc3d879f5, deletion_comment = False)

**Review by stacywray — APPROVED** [review]
Looks good.

**Comment by michaelcfanning** [comment]
yong, why didn't you merge this?

**Pull request closed without merging**
