### PR TITLE
HdfConverter: SARIF location improvements

### PR DESCRIPTION
**Pull request by candrews**
* Hdf: SourceLocation's Line and Ref are optional
   See: https://github.com/mitre/heimdall2/blob/v2.6.59/libs/inspecjs/src/generated_parsers/v_1_0/exec-json.ts#L311
* HdfConverter: Set ArtifactLocation and Region using SourceLocation
* HdfConverter: GitHub requires the uri to have a non-empty string value
   @michaelcfanning The validator at https://sarifweb.azurewebsites.net/Validation only checks that `uri` is present, it doesn't complain when `uri` is set to empty string. However, GitHub does complain, failing with `locationFromSarifResult: expected artifact location` as shown at https://github.com/candrews/jumpstart/actions/runs/5684090175/job/15406260757?pr=884#step:10:23
  How can  I contact whoever runs https://sarifweb.azurewebsites.net/Validation to tell them that it should report a problem when `physicalLocation.artifactLocation.uri=""`?

### CODE REVIEW

**Comment by candrews** [comment]
@michaelcfanning could you please take a look at this when you get a chance?

**Comment by michaelcfanning** [comment]
Will jump on this today or tomorrow, sorry for the delay.

**Comment by candrews** [comment]
> Will jump on this today or tomorrow, sorry for the delay.

Thank you again for working with me on this project! If you have any questions about this or https://github.com/microsoft/sarif-sdk/pull/2705 I look forward to promptly addressing them.

**Comment by candrews** [comment]
@michaelcfanning could you please take a look?

Thank you again!

**Review by michaelcfanning — CHANGES_REQUESTED** [review]
:clock1:

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Review by michaelcfanning — APPROVED** [review]

**Comment by michaelcfanning** [comment]
Sorry for the egregious delay here, dropped the ball initially on review and then went out of town. :(

**Comment by michaelcfanning** [comment]
Updated your release notes and will now merge.

**Pull request merged**
