### PR TITLE
Update GitHub brand names

### PR DESCRIPTION
**Pull request by jhutchings1**
👋🏻  Hey @michaelcfanning, I saw that we've got some brand inconsistencies in the SARIF SDK for some of the GitHub-specific validation rules. DSP is our internal organization name, but not our official product name, so I went and made a bunch of changes to align with the guidance from marketing. I don't have a working Windows dev environment to build/test this, although the prebuild.sh script works. Do you mind validating that this works as expected and merging if it's all good? 

Thank you!

### CODE REVIEW

**Comment by lgolding** [comment]
> #!/bin/bash

This file and RunTests.cmd show no textual differences, but the mode has changed. Why is this? I don't expect any changes to these files:
```
diff --git a/BeforeBuild.sh b/BeforeBuild.sh
old mode 100644
new mode 100755
diff --git a/RunTests.cmd b/RunTests.cmd
old mode 100644
new mode 100755
```

---
Refers to: BeforeBuild.sh:1 in ef4c8c0. [](commit_id = ef4c8c0c3e1e9fdc3cf429bb92e7624c5298bc06, deletion_comment = True)

**Comment by lgolding** [comment]
> #!/bin/bash

Looking more closely, if you open this PR in CodeFlow, it appears as if BeforeBuild.sh has now been moved into a _folder_ of the same name, and similarly with RunTests.cmd. Yet from the command line, that doesn't seem to be the case (and I confirm that I am on your branch:
```
C:\dev\sarif-sdk>dir /s BeforeBuild.sh
 Volume in drive C has no label.
 Volume Serial Number is 2641-AB48

 Directory of C:\dev\sarif-sdk

09/14/2020  01:01 PM               540 BeforeBuild.sh
               1 File(s)            540 bytes

     Total Files Listed:
               1 File(s)            540 bytes
               0 Dir(s)  747,344,420,864 bytes free

C:\dev\sarif-sdk>git branch
* branding
  master
```

Do you understand what happened?

---
In reply to: [692283408](https://github.com/microsoft/sarif-sdk/pull/2069#issuecomment-692283408) [](ancestors = 692283408)

---
Refers to: BeforeBuild.sh:1 in ef4c8c0. [](commit_id = ef4c8c0c3e1e9fdc3cf429bb92e7624c5298bc06, deletion_comment = True)

**Comment by lgolding** [comment]
> }

GitHub shows add/delete pairs for two of the files, even though they were just renamed and edited. This is all fine.

---
Refers to: src/Test.FunctionalTests.Sarif/TestData/Multitool/ValidateCommand/ExpectedOutputs/DSP1004.ReviewArraysThatExceedConfigurableDefaults_Valid.sarif:28 in ef4c8c0. [](commit_id = ef4c8c0c3e1e9fdc3cf429bb92e7624c5298bc06, deletion_comment = True)

**Comment by lgolding** [comment]
Hi Justin, thank you for your contribution. I pulled your fork/branch, made some changes, and pushed back to your fork.

- Michael and I would like the rule name prefix to be `GH`. We stick to short all-caps identifiers in tool ids. ("SARIF" was an exception -- longer than I (at least) would have liked it to be, but we couldn't come up with a good abbreviation for what's already an acronym.)
- I renamed some test files that were still named "DSPxxx.sarif".
- I made a few corrections to the rule descriptions and result messages, and made sure everything was consistent between the ValidationRules markdown file, the resources file, the code comments, and the test files.

I'm concerned about this weird change to the "mode" for both BeforeBuild.sh and RunTests.cmd. Can you somehow cause that to go away?

Once you have done that, please let me and Michael know and we'll merge it. Thanks again!

**Review by lgolding — APPROVED** [review]
:shipit:

**Comment by lgolding** [comment]
@jhutchings1 I understand the file mode change now (thanks to @michaelcfanning ), so I merged. The screen shot I pasted above just shows that CodeFlow doesn't understand how to represent that change. I'll file a bug on CodeFlow.

**Comment by jhutchings1** [comment]
Thanks @lgolding ! Is this deployed automatically? If not, let me know when it's live. Thanks!

**Comment by lgolding** [comment]
Hi @jhutchings1, sorry for the delay. We have a problem with our NuGet publishing pipeline so @michaelcfanning has to perform most of it manually.

The current status is that the SARIF packages version 2.3.6 (one _past_ the version that contained the re-branding) are published to NuGet. Michael's next step will be to update the [SARIF validation](http://sarifweb.azurewebsites.net/Validation) page to use the new branding.

Is that what you meant by "deployed", or was there something else?

**Comment by jhutchings1** [comment]
> Is that what you meant by "deployed", or was there something else?

Yep, that's what I meant. I'll wait for the update to the SARIF validation page :)

**Comment by michaelcfanning** [comment]
We've nearly fixed up our publishing infrastructure. It turns out that several small problems had accrued that have been revealing themselves one-by-one. :) I will reach out with status (and a report of success I hope) by EOD.

**Comment by michaelcfanning** [comment]
While we're here, we might as well ask you, what's your preference for labelling the GitHub Advanced Security code scanning rules? :) Would 'GitHub ingestion rules' suffice? Are you using 'GHAS' or some other acronym as preferred branding? Or would you like a more expansive description?

**Comment by lgolding** [comment]
@jhutchings1, the updated web site is deployed:

image

**Comment by lgolding** [comment]
@jhutchings1 As @michaelcfanning said, if you prefer something other than "GitHub ingestion rules" please let us know. We just wanted to get the bulk of the new branding deployed ASAP.

**Comment by jhutchings1** [comment]
Works for me! Thank you for getting this out so quickly!

**Pull request merged**
