### PR TITLE
Call overridable initialization mechanism. Update to 1.4.31

### PR DESCRIPTION
**Pull request by michaelcfanning**
@lgolding @rtaket

### CODE REVIEW

**Comment by lgolding** [comment]
Why is the method `virtual`? Is the idea to allow the configuration to be read from someplace other than the file specified in `analyzeOptions.ConfigurationFilePath`?

**Comment by lgolding** [comment]
(In any case, don't wait on me.)

**Comment by michaelcfanning** [comment]
This is the code path that produces a configuration property bag based on command-line parameters. If you override this method, you have the opportunity, as a driver, to accomplish two things: 1) populate non-default values in your custom configuration, 2) populate arbitrary other state based on command-line arguments.

in the binary checker, binskim, we override this method in order to set a new symbols path, that's relevant when loading PDBs. this value is pushed onto a static member on the Pdb wrapper class.

**Comment by lgolding** [comment]
@michaelcfanning In that case:

1. The method needs a comment explaining what it's for.

2. The name and the signature of the method are a little misleading. The fact that the method is named `CreateConfigurationFromOptions` and that it returns a `PropertyBag` suggests that its purpose in life is to create a property bag that represents the configuration, but in fact in binskim you also use it to populate a property "symbol path" on a completely unrelated class "PDB wrapper". Consider whether you might want to split these two functions ("populate the property bag", "perform other initialization") into two separate methods. You might restore the method you removed (`InitializeFromOptions`) to do the latter.

**Comment by lgolding** [comment]
Really I think that renaming the method `InitializeFromOptions` and giving it a good comment would suffice.

**Comment by michaelcfanning** [comment]
that was the original name. :P and then I realized this function was handled by a separate method.
will take your suggestion in a future change.

**Pull request merged**
